### ISSUE TITLE
Print  stack trace indention in logging correctly.

### ISSUE THREAD

**Issue by martins-1992** [www-splitcells-net/net.splitcells.network#30]
Example:
```
<?xml version="1.0" encoding="UTF-8"?>
<d:execution xmlns:d="http://splitcells.net/den.xsd"
             xmlns:n="http://splitcells.net/natural.xsd">
   <d:name>net.splitcells.website.martins.avots.HttpServer</d:name>
   <n:start-time>2021-03-22T00:56:40.200538+01:00[Europe/Berlin]</n:start-time>
   <d:error xmlns:d="http://splitcells.net/den.xsd">
      <d:message>java.nio.file.NoSuchFileException: ../net.splitcells.dem/src/main/xml</d:message>
      <d:stack-trace>java.lang.RuntimeException: java.nio.file.NoSuchFileException: ../net.splitcells.dem/src/main/xml
   	at net.splitcells.website.server.renderer.ProjectRenderer.projectLayout(ProjectRenderer.java:191)
   	at net.splitcells.website.server.renderer.ProjectsRenderer.lambda$projectsLayout$10(ProjectsRenderer.java:121)
   	at java.base/java.util.HashMap$Values.forEach(HashMap.java:976)
   	at net.splitcells.website.server.renderer.ProjectsRenderer.projectsLayout(ProjectsRenderer.java:107)
   	at net.splitcells.website.server.renderer.ProjectsRenderer.build(ProjectsRenderer.java:41)
   	at net.splitcells.website.server.renderer.ProjectsRenderer.serveToHttpAt(ProjectsRenderer.java:63)
   	at net.splitcells.website.martins.avots.HttpServer.lambda$main$0(HttpServer.java:22)
   	at net.splitcells.dem.Dem.lambda$process$1(Dem.java:63)
   	at java.base/java.lang.Thread.run(Thread.java:834)
   Caused by: java.nio.file.NoSuchFileException: ../net.splitcells.dem/src/main/xml
   	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
   	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
   	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
   	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
   	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
   	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
   	at java.base/java.nio.file.Files.readAttributes(Files.java:1764)
   	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
   	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
   	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
   	at java.base/java.nio.file.FileTreeIterator.&lt;init&gt;(FileTreeIterator.java:71)
   	at java.base/java.nio.file.Files.walk(Files.java:3825)
   	at java.base/java.nio.file.Files.walk(Files.java:3879)
   	at net.splitcells.website.server.renderer.ProjectRenderer.projectLayout(ProjectRenderer.java:187)
   	... 8 more
   </d:stack-trace>
   </d:error>
```

**Comment by martins-avots** [comment]
This is irrelevant for now.
